name: "Docspro"
author: "Jalkhov"
description: "Get translation progress from docs"
inputs:
  path:
    description: "Path to docs files"
    required: true
  multilang:
    description: "The project have multiple languages"
    required: false
    default: false
  ignore-languages:
    description: "Check all languages expect this one, comma separated list"
    required: false
    default: ""
outputs:
  progress:
    description: "Progress from project"
branding:
  icon: "percent"
  color: "red"
runs:
  using: "docker"
  image: "Dockerfile"
