name: "Docspro"
author: "Jalkhov"
description: "Get translation pogress from docs"
inputs:
  path:
    description: "Path to translation folder"
    required: true
outputs:
  progress:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
