name: "Docspro"
author: "Jalkhov"
description: "Get translation pogress from docs"
inputs:
  path:
    description: "Path to translation folder"
    required: true
outputs:
  progress:
    description: "Total progress from project"
branding:
  icon: "percent"
  color: "red"
runs:
  using: "docker"
  image: "Dockerfile"
