name: "Docspro"
author: "Jalkhov"
description: "Get translation pogress from docs"
inputs:
  path:
    description: "Path to translation folder"
    required: true
  token:
    description: "GitHub Secret Token; if not given the check result is not attached to the commit."
    required: false
    default: ""
outputs:
  progress:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
