name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docs-Pro
        id: docspro
        uses: Jalkhov/docs-pro@master
        with:
          path: "translations/**/*.po"

      - name: Check outputs
        run: |
          test "${{ steps.docspro.outputs.progress }}" == "Hola"
