name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: Jalkhov/docs-pro@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          translations_path: 'translations/**/*.po'

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.progress }}"
