name: Test multiple cases
on: [push, pull_request]
jobs:
  progress-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

        # This return a string with the progress of pointed lang
      - name: Single language
        id: single_lang
        uses: Jalkhov/docs-progress@v1.0.0
        with:
          path: "docs/locales/es"

        # This return a dict with each lang and it progress
      - name: Multiple languages
        id: multi_lang
        uses: Jalkhov/docs-progress@v1.0.0
        with:
          path: "docs/locales"
          multilang: true

        # This return a dict with each lang and it progress,
        # but ignoring zh_CN lang
      - name: Multiple languages ignoring one
        id: multi_lang_ignore
        uses: Jalkhov/docs-progress@v1.0.0
        with:
          path: "docs/locales"
          multilang: true
          ignore-languages: "zh_CN"

        # This calculate entire project progress (all langs)
      - name: Entire project
        id: full_project
        uses: Jalkhov/docs-progress@v1.0.0
        with:
          path: "docs/locales"

        # This calculate entire project progress (all langs)
        # ignoring one lang
      - name: Entire project ignoring one
        id: full_project_ignore
        uses: Jalkhov/docs-progress@v1.0.0
        with:
          path: "docs/locales"
          ignore-languages: "zh_CN"

      - name: Check outputs
        run: |
              echo "Single language (es): ${{ steps.single_lang.outputs.progress }}%
              Multiple languages: ${{ steps.multi_lang.outputs.progress }}
              Multiple languages ignoring zh_CN: ${{ steps.multi_lang_ignore.outputs.progress }}
              Entire project: ${{ steps.full_project.outputs.progress }}%
              Entire project ignoring zh_CN: ${{ steps.full_project_ignore.outputs.progress }}%"
