name: Basic usage example
on: [push, pull_request]
jobs:
  progress-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get Spanish translation progress
        id: es_progress
        uses: Jalkhov/docs-progress@master
        with:
          path: "docs/locales/es"

      - name: Check outputs
        run: |
              echo "Outputs - ${{ steps.es_progress.outputs.progress }}%"
